config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :concert_halls
  resources :bands
  mount Attachinary::Engine => "/attachinary"
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  STYLES = ["Blues", "chanson française", "Disco", "Rock", "Funk", "Jazz Manouche", "Métal", "Musique Classique", "Salsa", "Techno", "World", "Folk", "Zouk", "Slam", "Soul", "Reggae", "Dub", "Hardrock", "Country", "Rap", "Rnb", "House", "Jazz", "Indie Rock", "Pop", "Hip Hop", "Dance"]

  has_many :events

  validates :name, presence: true
  validates :description, presence: true
  validates :style, inclusion: { in: STYLES, allow_nil: false }
  validates :rating, inclusion: { in: [0,1,2,3,4,5], allow_nil: false }, numericality: { only_integer: true }
  validates :url, format: { with: /https?:\/\/[\S]+/ }

  has_attachment :photo
end

app/models/concert_hall.rb
class ConcertHall < ApplicationRecord
  has_many :events

  validates :name, presence: true
  validates :address, presence: true

  has_attachment :photo
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :band
  belongs_to :concert_hall

  validates :date, presence: true
  validates :price, numericality: { only_integer: true }

  has_attachment :photo
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :set_band, only: [:show, :edit, :update, :destroy]

  # GET /bands
  # GET /bands.json
  def index
    @bands = Band.all
  end

  # GET /bands/1
  # GET /bands/1.json
  def show
  end

  # GET /bands/new
  def new
    @band = Band.new
  end

  # GET /bands/1/edit
  def edit
  end

  # POST /bands
  # POST /bands.json
  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_path(@band)
    else
      render :new
    end
  end

  # PATCH/PUT /bands/1
  # PATCH/PUT /bands/1.json
  def update
    @band.update(band_params)
    @band.save
    if @band.save
      redirect_to band_path(@band)
    else
      render :new
    end
  end

  # DELETE /bands/1
  # DELETE /bands/1.json
  def destroy
    @band.destroy
    respond_to do |format|
      format.html { redirect_to bands_url, notice: 'Band was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band
      @band = Band.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_params
      params.require(:band).permit(:name, :style, :description, :rating, :url, :photo)
    end
end

app/controllers/concert_halls_controller.rb
class ConcertHallsController < ApplicationController
  before_action :set_hall, only: [:show, :edit, :update, :destroy]

  def index
    @concert_halls = ConcertHall.all
  end

  def show
  end

  def new
    @concert_hall = ConcertHall.new
  end

  def create
    @concert_hall = ConcertHall.new(concert_hall_params)
    @concert_hall.save
    if @concert_hall.save
      redirect_to concert_hall_path(@concert_hall)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @concert_hall.update(concert_hall_params)
    redirect_to concert_hall_path(@concert_hall)
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hall
      @concert_hall = ConcertHall.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concert_hall_params
      params.require(:concert_hall).permit(:name, :address, :photo)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save
    if @event.save
      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @event.update(event_params)
    redirect_to event_path(@event)
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :price, :band_id, :concert_hall_id, :photo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/concert_halls_helper.rb
module ConcertHallsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/bands/_form.html.erb
 <div class="row">
  <%= simple_form_for [@band] do |f| %>
  <div class="col-xs-12 col-sm-6">
      <div><%= f.input :name %></div>
      <div><%= f.input :style, collection: Band::STYLES, prompt: "Select" %></div>
      <div><%= f.input :description %></div>
      <div><%= f.input :rating, collection: (0..5)%></div>
      <div><%= f.input :url %></div>
      <%= f.submit %>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div><%= f.input :photo, as: :attachinary %></div>
  </div>
    <% end %>
</div>

app/views/bands/edit.html.erb
<h1>Modifier Groupe</h1>

<%= render 'form', band: @band %>

<%= link_to 'Voir', @band %> |
<%= link_to 'Back', bands_path %>

app/views/bands/index.html.erb
<h1>Groupes</h1>

  <div class="row">
    <% @bands.each do |band| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
        <div class="card-category"><h2><%= band.name %></h2></div>
        <div class="card-description">
            <p>Style: <%= band.style %> --- Rating: <%= band.rating %></p>
            <%= link_to 'Show', band %>
            <%= link_to 'Edit', edit_band_path(band) %>
            <%= link_to 'Destroy', band, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
      <br/>
    <%= link_to 'New Band', new_band_path %>

app/views/bands/new.html.erb
<h1>Nouveau Groupe</h1>

<%= render 'form', band: @band %>

<%= link_to 'Back', bands_path %>

app/views/bands/show.html.erb
<p id="notice"><%= notice %></p>

<div class="media">
  <div class="media-body">
    <div class="media-section">
      <h2>Pictures</h2>
    </div>
    <div class="media-section">
      <h2><%= @band.name %></h2>
      <p>
        <%= @band.description %>
      </p>
      <%= link_to 'Edit', edit_band_path(@band) %> |
      <%= link_to 'Back', bands_path %>
    </div>
  </div>
  <div class="media-aside">
    <div class="media-section">
      <h2>Share</h2>
      <div class="share-links">
        <a href="#" class="share-link bg-facebook">
          <i class="fa fa-facebook"></i>
        </a>
        <a href="#" class="share-link bg-twitter">
          <i class="fa fa-twitter"></i>
        </a>
        <a href="#" class="share-link bg-email">
          <i class="fa fa-envelope-o"></i>
        </a>
        <a href="#" class="share-link bg-text">
          <i class="fa fa-mobile"></i>
        </a>
      </div>
      <p>
        <strong>Url:</strong>
        <%= @band.url %>
      </p>
    </div>
    <div class="media-section">
      <h2>Style</h2>
      <p>
        <%= @band.style %>
      </p>
      <h2>Rating</h2>
      <p>
        <%= @band.rating %>
      </p>
    </div>
  </div>
</div>

app/views/concert_halls/_form.html.erb
 <div class="row">
  <%= simple_form_for [@concert_hall] do |f| %>
  <div class="col-xs-12 col-sm-6">
      <div><%= f.input :photo, as: :attachinary %></div>
      <div><%= f.input :name %></div>
      <div><%= f.input :address%></div>
      <%= f.submit %>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div><%= f.input :photo, as: :attachinary %></div>
  </div>
    <% end %>
</div>

app/views/concert_halls/edit.html.erb
<h1>Salle</h1>

<%= render 'form', concert_hall: @concert_hall %>

<%= link_to 'Show', @concert_hall %> |
<%= link_to 'Back', concert_halls_path %>

app/views/concert_halls/index.html.erb
<h1>Salles</h1>
  <div class="row">
    <% @concert_halls.each do |hall| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
        <div class="card-category"><h2><%= hall.name %></h2></div>
        <div class="card-description">
            <%= hall.address %>
            <br/>
            <%= link_to 'Voir', hall %>
            <%= link_to 'Modifier', edit_concert_hall_path(hall) %>
            <%= link_to 'Supprimer', hall, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
      <br/>
    <%= link_to 'Ajouter une salle', new_concert_hall_path %>

app/views/concert_halls/new.html.erb
<h1>Ajouter une salle</h1>

<%= render 'form', concert_hall: @concert_hall %>

<%= link_to 'Back', concert_halls_path %>

app/views/concert_halls/show.html.erb
<h2><%= @concert_hall.name %></h2>

<p>
  <strong>Style:</strong>
  <%= @concert_hall.address %>
</p>

<%= link_to 'Edit', edit_concert_hall_path(@concert_hall) %> |
<%= link_to 'Back', concert_halls_path %>

app/views/events/_form.html.erb
<div class="row">
  <%= simple_form_for [@event] do |f| %>
  <div class="col-xs-12 col-sm-6">
      <div><%= f.input :date %></div>
      <div><%= f.input :price %></div>
      <div><%= f.input :band_id, collection: Band.all %></div>
      <div><%= f.input :concert_hall_id, collection: ConcertHall.all %></div>
      <%= f.submit %>
  </div>
  <div class="col-xs-12 col-sm-6">
    <div><%= f.input :photo, as: :attachinary %></div>
  </div>
    <% end %>
</div>

app/views/events/edit.html.erb
<h1>Mettre à jour l'événement</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Concerts</h1>

  <div class="row">
    <% @events.each do |event| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('background.jpg');">
        <div class="card-category"><%= event.date %></div>
        <div class="card-description">
          <h2>Info</h2>
            <%= event.price %>
            <% if event.band_id? %>
              <%= event.band.name %>
            <% end %>
            <% if event.concert_hall_id? %>
              <%= event.concert_hall.name %>
            <% end %>
            <br/>
            <%= link_to 'Show', event %>
                <%= link_to 'Edit', edit_event_path(event) %>
                <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
    <% end %>

  </div>
      <br/>
    <%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>Nouveau concert</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1>Event</h1>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
<% if @event.concert_hall_id? %>
  <strong>Description:</strong>
  <%= @event.concert_hall.name %>
<% end %>
</p>

<p>
<% if @event.band_id? %>
  <strong>Rating:</strong>
  <%= @event.band.name %>
<% end %>
</p>



<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/lewagon.png" />
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Contact</a>

    <!-- Text link -->
    <a href="" class="navbar-wagon-item navbar-wagon-link">Team</a>

    <!-- Notification link-->
    <a href="" class="navbar-wagon-item navbar-wagon-link">
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    </a>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <a href="" class="navbar-wagon-item navbar-wagon-button btn">Post stuff</a>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_tag("htmujwbi3hqfdu0jch4c", width: 1300, height: 500, crop: :fill) %>');">
    <div class="card-description">
      <h1>TOUS LES CONCERTS A LILLE</h1>
    </div>
    <p><a class="btn btn-primary btn-lg" href="/bands" role="button">GROUPES</a></p>
    <p><a class="btn btn-primary btn-lg" href="/events" role="button">EVENEMENTS</a></p>
    <p><a class="btn btn-primary btn-lg" href="/concert_halls" role="button">SALLES</a></p>

</div>


<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_tag('htmujwbi3hqfdu0jch4c', width: 1300, height: 500, crop: :fill) %>');">
  <div class="card-category">Popular</div>
  <div class="card-description">
    <h2>Some stuff</h2>
    <p>Very cool stuff, useful and smart</p>
  </div>
  <img class="card-user avatar" src="user.jpg">
  <a class="card-link" href="#" ></a>
</div>